#!/usr/bin/env python3

import sys
from actions.action import action

sys.argv.pop(0)

def process(given):
  decision = action.do('think', given) # think of something
  action.do(decision.act, decision.on) # act on the decision


if(__name__ == '__main__'):
  process(sys.argv)
